Code added
mortawe/IZ2 pull request #4
Opened 2019-10-22 19:35 UTC by mortawe

2019-10-22 19:36 UTC, mortawe commented
Сделала по-деревенски, потому что с rebase все равно не получилось! =(

2019-10-24 09:59 UTC, leshiy1295 requested changes

2019-10-24 09:59 UTC, leshiy1295 commented on .travis.yml
> +  - sudo make
зачем sudo в каждой команде?

2019-10-24 09:59 UTC, leshiy1295 commented on .travis.yml
> +script:   "valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./IZ2"
почему не запускались тесты под valgrind?

2019-10-24 09:59 UTC, leshiy1295 commented on .travis.yml
> +  - make
нет проверки статическими анализаторами + coverage

2019-10-24 09:59 UTC, leshiy1295 commented on .travis.yml
> +language: c
сейчас запускается 2 одинаковых билда на каждый пуш
это неправильно

2019-10-24 09:59 UTC, leshiy1295 commented on .travis.yml
> +    - test@gmail.com
зачем?

2019-10-24 09:59 UTC, leshiy1295 commented on README.md
> +[![Build Status](https://travis-ci.org/mortawe/IZ2.svg?branch=master)](https://travis-ci.org/mortawe/IZ2)
стоит отображать значки прямо в Pull Request

2019-10-24 09:59 UTC, leshiy1295 commented on example/example_1.c
> +#include "../include/sequential.h"
относительных include быть не должно. Их наличие свидетельствует о неправильной настройке CMake

2019-10-24 09:59 UTC, leshiy1295 commented on example/example_1.c
> +    const size_t memory_size = 100 * 1024 * 1024;
программа должна работать для произвольных размеров входных данных
100 Мб дано в качестве примера размера, на котором имеет смысл проверять эффективность алгоритмов и осуществлять замеры

2019-10-24 09:59 UTC, leshiy1295 commented on example/example_1.c
> +    clock_t begin = clock();
clock не так работает с потоками, как Вы это ожидаете

2019-10-24 09:59 UTC, leshiy1295 commented on example/example_1.c
> +    sequential(memory_size);
интерфейс у обеих библиотек должен быть одинаковый
необходимо подключать ту или другую библиотеку в зависимости от флагов компиляции/аргументов командной строки

2019-10-24 09:59 UTC, leshiy1295 commented on include/parallel.h
> +#define ERROR_MALLOC -11
магические константы...
лучше оформлять в виде enum

2019-10-24 09:59 UTC, leshiy1295 commented on include/parallel.h
> +int * fill_array_parallel(int *, int, int );
названия параметров тоже важны в сигнатуре функции
сейчас совершенно непонятно, что она принимает на вход

2019-10-24 09:59 UTC, leshiy1295 commented on include/parallel.h
> +//
.h файл должен быть общим для обеих реализаций и не раскрывать особенностей реализации (например, pthread)

2019-10-24 09:59 UTC, leshiy1295 commented on include/sequential.h
> +#ifndef T2_SEQUENTIAL_H
почему этот код находится где-то внутри?

2019-10-24 09:59 UTC, leshiy1295 commented on include/sequential.h
> +#include <pthread.h>
зачем в sequential этот заголовочный файл?

2019-10-24 09:59 UTC, leshiy1295 commented on include/sequential.h
> +#include <time.h>
time.h тоже внутри библиотеки не нужен, так как все замеры должны осуществляться извне

2019-10-24 09:59 UTC, leshiy1295 commented on source/parallel.c
> +        exit(ERROR_MALLOC);
нельзя выходить из потока с помощью exit

2019-10-24 09:59 UTC, leshiy1295 commented on source/parallel.c
> +            exit(ERROR_MALLOC);
нужно корректно обрабатывать все ошибки работы с памятью, корректно освобождая всю выделеную и завершая выполнение потока, а не всей программы

2019-10-24 09:59 UTC, leshiy1295 commented on source/parallel.c
> +    pthread_t threads[threads_num];
что если threads_num <= 0?

2019-10-24 09:59 UTC, leshiy1295 commented on source/parallel.c
> +    fill_array_parallel(a, array_size, 10);
10 - магическая константа
точное количество потоков должно зависеть от environment, в котором программа выполяется
если всего есть 1 ядро, то использовать 10 потоков крайне неэффективно

2019-10-24 09:59 UTC, leshiy1295 commented on source/parallel.c
> +    //printf("thread [%d,%d)\n", data->from, data->to);
комментариев с нерабочим кодом быть не должно

2019-10-24 09:59 UTC, leshiy1295 commented on source/parallel.c
> +        *(data->a + i) = count;
что если data == NULL?

2019-10-24 09:59 UTC, leshiy1295 commented on source/parallel.c
> +        count = (count + 1) % 4;
магические константы...

2019-10-24 09:59 UTC, leshiy1295 commented on source/sequential.c
> +    for (int i = 0; i < n; i++) {
код очень напоминает код выше
почему бы их не объединить и не переиспользовать?

2019-10-24 09:59 UTC, leshiy1295 commented on test/unit_test.cpp
> +    int status = sequential(memory_size);
status ни о чём не говорит
полезно сравнивать итоговый массив с правильным результатом
+ нужны стресс-тесты, которые запускают одновременно на больших размерах случайных входных данных последовательную и параллельную реализации и сравнивают их результаты между собой

2019-10-24 09:59 UTC, leshiy1295 commented on test/unit_test.cpp
> +    a = fill_array_parallel(a, memory_size / sizeof(int), 50);
какой смысл тестировать количество потоков?
это было бы интересно, если проводились бы замеры

2019-10-24 09:59 UTC, leshiy1295 commented on test/unit_test.cpp
> +    pthr_data *data = (pthr_data *) malloc(sizeof(pthr_data ));
что если a == NULL?

2019-10-24 09:59 UTC, leshiy1295 commented on test/unit_test.cpp
> +            exit(ERROR_CREATE_PTHREAD);
в этом случае free выполнены не будут

2019-10-24 18:16 UTC, mortawe commented on .travis.yml
> +language: c
Поясните, пожалуйста, что именно не так D: 
Дублируется, вроде бы, только запуск ./IZ2 - один раз под валгриндом, другой без

2019-10-24 18:16 UTC, mortawe commented on .travis.yml
> +script:   "valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./IZ2"
Исправлю. 
Вообще все запускать только под валгринд один раз?

2019-10-24 18:17 UTC, leshiy1295 commented on .travis.yml
> +language: c
я про CI-сборки... Если посмотрите на результаты, то увидите, что их там две, и они совершенно одинаковые

2019-10-24 18:18 UTC, leshiy1295 commented on .travis.yml
> +script:   "valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./IZ2"
тестов обычно много, и они должны покрывать значительную часть кода => логично запускать их с valgrind

2019-10-24 18:28 UTC, mortawe commented on .travis.yml
> +language: c
Хм, это начало происходить после 36 попытки сборки, когда я перестала следить за тревисом.
Предполагаю, что я в этот момент сделала пул реквест  и из-за 
```
branches:
  only:
    - master
    - dev
```
билды начали дублироваться. 

Или  я ошибаюсь? 
Перечитала .yml файл , причину найти не смогла

2019-10-24 18:46 UTC, mortawe commented on test/unit_test.cpp
> +    int status = sequential(memory_size);
Случайные входные данные это какие данные? 
Количество потоков/размер массива?

2019-10-24 18:47 UTC, leshiy1295 commented on test/unit_test.cpp
> +    int status = sequential(memory_size);
Количество потоков - это реализация... Причём его нужно выбирать в зависимости от системы, на которой программа запускается.
Внешними данными является массив...

2019-10-24 19:17 UTC, mortawe commented on include/sequential.h
> +#ifndef T2_SEQUENTIAL_H
Какой? 
#ifndef?

2019-10-24 19:19 UTC, leshiy1295 commented on include/sequential.h
> +#ifndef T2_SEQUENTIAL_H
да

2019-10-24 20:41 UTC, mortawe commented on source/parallel.c
> +        *(data->a + i) = count;
В fill_array_parallel проверяются на NULL все такие  data. Нужна еще одна проверка?

2019-10-24 20:47 UTC, leshiy1295 commented on source/parallel.c
> +        *(data->a + i) = count;
Это другой метод - вызывающая сторона. Никаких гарантий соблюдения вызывающей стороной контрактов на стороне вызываемой функции нет. Аналогично - никаких гарантий нет и на стороне вызываемой функции (что некорректные параметры корректно обрабатываются функцией). Поэтому в парадигме безопасного программирования нужно проверять выполнение контрактов и там, и там...

2019-10-24 20:51 UTC, mortawe commented on source/parallel.c
> +        exit(ERROR_MALLOC);
Здесь потоков, вроде бы, еще нет, просто завершение программы после неудачного маллока.
А как правильно поступать, когда pthread_create возвращает не 0? Освобождать память, завершать потоки етц и завершать программу, или продолжать пытаться создать поток?

2019-10-24 20:52 UTC, leshiy1295 commented on source/parallel.c
> +        exit(ERROR_MALLOC);
корректно завершать текущий поток с возвратом кода ошибки, чтобы родительский процесс эту ситуацию как-то мог обработать
на стороне выходящего потока нужно корректно освободить все ресурсы

2019-10-25 12:12 UTC, mortawe commented on include/parallel.h
> +//
то есть должно быть три хедера, общий и для двух реализаций? Или pthread в .с файл вставлять?

2019-10-25 12:52 UTC, leshiy1295 commented on include/parallel.h
> +//
нет, должен быть один хедер, который будет подключаться в тестах и в main, который будет описывать сигнатуру вызываемой функции
а вот реализация этой функции должна быть разная в библиотеках, и внутри каждой из них вполне могут использоваться какие-то внутренние (приватные, недоступные извне) хедеры

2019-10-25 13:35 UTC, mortawe commented on include/parallel.h
> +//
Поняла.
А как специфицировать функцию библиотеки, если к одному .с подключены обе?

2019-10-25 15:01 UTC, mortawe commented on include/parallel.h
> +//
не нашла способ, сделала с fork и exec

2019-10-25 16:12 UTC, mortawe commented on .travis.yml
> +  - make
А gcvr будет работать с .c? 
У меня он видит только .cpp

2019-11-03 15:15 UTC, leshiy1295 reviewed
очень хорошая работа!

2019-11-03 15:15 UTC, leshiy1295 commented on example/example_1.c
> +    int * const ref_array = calloc(array_size, sizeof(int));
тесты - тоже код
тут нужно корректно обрабатывать ошибки
calloc может упасть

2019-11-03 15:15 UTC, leshiy1295 commented on example/example_2.c
> +        printf("time : %f \n", elapsed);
хотелось бы, конечно, увидеть результаты замеров в самом Merge Request...

2019-11-03 15:15 UTC, leshiy1295 commented on gcov/code_coverage_report.example_example_1.c.html
> +<html>
отчёты хранить в репозитории нет смысла - это временные генерируемые файлы, которые должны появляться на CI
в репозитории достаточно хранить только код их генерации

2019-11-03 15:15 UTC, leshiy1295 commented on include/fill_array.h
> +#include <pthread.h> //нужен example для замера времени
если он нужен example, то внутри example его подключить и стоило

2019-11-03 15:15 UTC, leshiy1295 commented on include/fill_array.h
> +void * thread_routine(void * arg);
это детали реализации...

2019-11-03 15:15 UTC, leshiy1295 commented on include/fill_array.h
> +    int * a; //array_to_fill
можно было бы, например, переменную так и назвать :)
комментарий бы не понадобился + в любом месте программы было бы ясно, что это за поле

2019-11-03 15:15 UTC, leshiy1295 commented on source/parallel.c
> +                data[threads_num]->a = array_to_fill;
стоило вынести в функцию инициализации структуры

2019-11-03 15:15 UTC, leshiy1295 commented on source/parallel.c
> +                    threads_num++;
предпочитайте ++i вместо i++

2019-11-03 15:15 UTC, leshiy1295 commented on source/parallel.c
> +        if (is_array_full == 1) break;
не стоит экономить на {} и переносах строк

2019-11-03 15:15 UTC, leshiy1295 commented on source/parallel.c
> +            if (!used_index[i]){
если уж и использовать неструктурные операторы, то тут лучше было бы написать
if (used_index[i]) { continue; }
чтобы дальше уже без отступов шёл весь код
вообще - использовать break в таком количестве - не самая хорошая идея... Всё же анализировать такой код намного сложнее, чем структурный

2019-11-03 15:15 UTC, leshiy1295 commented on test/unit_test_par.cpp
> +        exit(ERROR_MALLOC);
не очень здорово завершать тест простым exit

2019-11-03 15:15 UTC, leshiy1295 commented on test/unit_test_par.cpp
> +    pthread_create(&thread1, NULL, thread_routine, data1);
это внутренние детали реализации
если хотелось бы протестировать их, стоило завести приватный header-файл, который использовать внутри библиотеки и тут, в тесте

2019-11-03 15:15 UTC, leshiy1295 commented on example/example_with_both_libs.cpp
> +int main(  ) {
какой смысл в этом таргете? :)
для стресс-теста нужно было ещё сравнить результаты работы этих программ...

2019-11-04 08:41 UTC, mortawe commented on example/example_with_both_libs.cpp
> +int main(  ) {
Что именно Вы подразумеваете под "таргетом"?
В этом примере была предпринята попытка реализовать то, что требовалось в письме. Другим способом две библиотеки использовать не удавалось =(

2019-11-04 08:43 UTC, leshiy1295 commented on example/example_with_both_libs.cpp
> +int main(  ) {
Таргет - это итоговый бинарник.
Нужно было просто ещё им подать что-то на вход и сравнить их выводы между собой.
В остальном - всё ок

2019-11-04 09:20 UTC, mortawe commented on example/example_with_both_libs.cpp
> +int main(  ) {
А нужно ли сравнивать выводы  реализаций между собой, если в тестах я  уже проверяла каждую из библиотек на корректность вывода ?

2019-11-04 09:24 UTC, leshiy1295 commented on example/example_with_both_libs.cpp
> +int main(  ) {
Тесты каждой библиотеки - на заранее известных наборах данных, которых ограниченное число. Для случайного большого объёма данных ответ заранее неизвестен. Стресс-тесты позволяют избежать этого, поскольку ответы генерируются одним из алгоритмов (как правило, более простым) автоматически.

2020-07-26 14:39 UTC, merged